# Generated by Django 5.1.3 on 2024-12-31 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_room_ended_at_room_score_player1_room_score_player2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='ball_position',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='room',
            name='ball_velocity',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='room',
            name='player1_position',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='room',
            name='player2_position',
            field=models.JSONField(default=dict),
        ),
    ]
