# Generated by Django 5.1.3 on 2024-12-31 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_gamehistory_delete_room'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamehistory',
            name='room_id',
            field=models.CharField(default='default_room', max_length=100),
        ),
    ]
